### ISSUE TITLE
chain-based recursion

### ISSUE THREAD

**Issue by rpominov** [rpominov/fun-task#17]
Currently we don't support infinite chain-based recursion like the following. Library will consume more and more memory as program runs in such case.

```js
// suppose this task never fails
const someTask = ...
const recur = () => someTask.chain(recur)
recur()
```

Things we should try:

- Create a method that basically does exactly what is going on above, so we could do `someTask.recur()`. This method still be usable if `someTask` fails (recursion won't be infinite)
- Create similar method but with `orElse` instead of `chain` — `someTask.retryUntilSuccess()`. Also useful if task succeeds eventually.
- Try to optimize these methods using low-level API and make them support infinite recursion.

**Comment by Avaq** [comment]
Related: https://github.com/Avaq/Fluture/issues/6

**Comment by Avaq** [comment]
And now, in 2.0: https://github.com/Avaq/Fluture#recur

**Comment by rpominov** [comment]
I'm working on `recur` that works like this:

```js
Task.of(5).recur(x => {
  x // 5, 4, 3, 2, 1, 0
  return x === 0 ? Task.rejected('done') : Task.of(x - 1) 
})
```

It's implemented https://github.com/rpominov/fun-task/commit/5ae9121b41f00c5d3ee1cc26a2ff271878041c10 and seems to work without memory leaks. Although I'm feeling a bit like doing [dog science](https://www.google.ru/search?q=dog+science&tbm=isch), tbh.

**Comment by rpominov** [comment]
I think it will be possible to also make it safe from "Maximum call stack size exceeded" error, although at this point I don't even 100% sure that it's safe from memory leaks.

**Comment by rpominov** [comment]
Thats was easier that I expected https://github.com/rpominov/fun-task/commit/b8d8dcaf563876fe0c8316aac979977df9b7ff17

And now I'm more confident that it doesn't have memory leaks because it's easier to test when I don't have to care about growing stack if I use sync tasks.

Needs more testing still...

This is basically a loose implementation of [`chainRec`](https://github.com/fantasyland/fantasy-land/pull/152), except `recur` is an [instance method](https://github.com/fantasyland/fantasy-land/pull/152#issuecomment-244557918) and uses built-in Either instead of `next/done`.

Not sure whether we should implement the spec or leave current `recur` API. I like the `recur` api because it's simpler than the spec. We should probably implement both APIs.

**Comment by safareli** [comment]
Implementing `ChainRec` spec is very important, as other structures could depend on the API to be stack safe. For example in my `Free` implementation would be stacksafe if structure to which the `Free` is foldMap-ed is also stack safe i.e implements ChainRec. Basically that's why i have started the issue/PR in fantasy land. [safareli/free/issues/22](https://github.com/safareli/free/issues/22)

for reference this is [implementation](https://github.com/safareli/free/blob/e5fbbde2c50a1ec61968ec7c529aa3bb8ea51841/src/tailRec.js#L25-L98) of ChainRec for `folktale/data.task` with [tests](https://github.com/safareli/free/blob/e5fbbde2c50a1ec61968ec7c529aa3bb8ea51841/test/tailRecM.js)
(it's not quite correct as it is not handling cleanup stuff of the data.task but without that it works well)

**Comment by rpominov** [comment]
I've released `1.3.0` that includes `recur()`. 

Going to add `chainRec()` eventually.

Also want to add `task.retry([maxRetriesNumber])` that would basically re-run the same task until it succeeds (or until it had been run `maxRetriesNumber` times, if that argument is provided).

**Comment by safareli** [comment]
Nice! once there are some libs implementing ChainRec I would also update `Free` to be ChainRec :3

**Comment by rpominov** [comment]
Implemented `ChainRec` in https://github.com/rpominov/fun-task/commit/cb06fdf490528c4360b94363120401dd71f1bb1e . Will release a new version soon.

Note to self: check also that `Task.do()` supports loops with number of steps bigger than max stack size.

**Comment by safareli** [comment]
@rpominov Brilliant work!

**Comment by rpominov** [comment]
Everything mentioned here is done and released, except `task.retry()` which is extracted to #27
