### ISSUE TITLE
Memoization (a method that creates a Promise-like task from normal task) 

### ISSUE THREAD

**Issue by rpominov** [rpominov/fun-task#2]
```js
const memoizedTask = task.memoize()
```

The `memoizedTask` will `run()` original `task` at most once, even if we do `memoizedTask.run()` many times. If we cancel a run of a memoized Task it will work as unsubscription and will not cancel original task.

Memoized Task is almost like Promise. We can give it to multiple consumers, and they'll all get the same result, also computation will run only once. The differences from Promise is that it's still lazy (runs original task only after the first `memoizedTask.run()`), and that we still can unsubscribe.

**Comment by rvikmanis** [comment]
Should `Promise` interop be added to memoized tasks (perhaps even normal tasks?) in the form of `memoizedTask.then()`?

**Comment by rpominov** [comment]
Not sure if adding `then` method for interop is a good idea, but I'm planning to add `toPromise`, thanks for reminder btw.

**Comment by rvikmanis** [comment]
I suppose you're right about implicit "thenability". 

How about making the return value of `run` a promise instead? I think it makes sense in the context of `Promise` being the result of computation, while `Task` is the computation.

**Comment by rpominov** [comment]
This is interesting idea. But there are some issues with this. First of all we already use return value of run for cancelation. Also the cancelation is also works as unsubscription, and if we return a promise we loose unsubscription feature (users will need to subscribe to promise which doesn't support unsubscription). The bottom line is I'm hopping to create better API in Task, in particular for subscribing/running, and if we delegate it to Promises we won't be able to improve it.

**Comment by rpominov** [comment]
Also there is the `runAndCatch` (see the table in readme) feature, which also won't fit with the idea of returning a promise from run.

This feature in fact was the main motivation for starting this project. Never saw anything like that in other implementations of Task/Future, and wanted to try to do this.

`runAndCatch` and cancelation is what makes this lib different from other Task/Future implementations like [data.task](https://github.com/folktale/data.task) or [fluture](https://github.com/Avaq/Fluture)

**Comment by rvikmanis** [comment]
Okay, I think I see the point. What if we return an object of the form `{ then, catch, cancel }`, and if upon cancellation there are subscribers, we could reject the promise.

**Comment by rpominov** [comment]
toPromise will run the task and return an object with `{then, catch}` (well a Promise 😆 ), so I think this is covered. If you suggest that instead of two methods we could fit everything to just one, I'm not a fun of such API design choices.

**Comment by rpominov** [comment]
A thought: maybe we shouldn't introduce `task.memoize()` and recommend to use `task.toPromise()` instead.

**Comment by rpominov** [comment]
One of problems with this is that we won't be able to tell whether `catch` callback is present or not. Because one of multiple "child" tacks could be run with `catch` and another without. So we would have to always  `catch` or never `catch` neither of which seems correct to me.

Also overall this method feels somewhat unnatural to this library. I think we should focus on `task.toPromise()` for this use-case for now. Closing this, but we can revisit later.
