### ISSUE TITLE
Promise.filter

### ISSUE THREAD

**Issue by bachstatter** [rpominov/fun-task#31]
Say I have an array of items. And I want to filter those base on an asynchronous action.

With a bluebird promise I can do this:
```
Promise.filter(xs, x =>
   asyncConditionFunction(x)
)
.then(filteredXs => console.log(filteredXs))
```

Do you know of any nice pattern do convert this to tasks?
When I tried it got messy quite quickly. Lets assume `asyncConditionFunction` return a task instead:
```
Task.of(xs)
.chain(xs =>
  Task.paralell(xs.map(x => asyncConditionFunction(x))
   .map(arrayWithBooleans => xs.filter((x, i) => arrayWithBooleans[i])) // This feels so wrong.
)
.map(xs => console.log(xs)) // xs has been filtered
```

Do you know any nicer pattern?

**Comment by rpominov** [comment]
Hey! Not sure a function like this actually makes sense for tasks. 

Unlike Promises a task may return different value each time it's ran. So if we have an array of tasks, and we run them in order to look at values inside, and filter the array based on that values, when we run tasks from the result array they may contain different values. 

Also running the tasks twice may be not what we want, as it will execute each effect twice (say send an http request twice).

So not sure this is a good pattern for tasks.

**Comment by bachstatter** [comment]
Yea my solution isn't a solution.. 

More real example:
I have an array of questions. I want to filter the questions so I only get those with answers.
A `hasQuestionBeenAnswered` function makes a http request and returns true if it has.
```
const questions = [
  ...
  {name: 'ex', id:1}
  ...
]
Promise.filter(questions, question =>
   hasQuestionBeenAnswered(question)
)
.then(answeredQuestions => console.log(answeredQuestions))
```

I wanted to try to convert this to a task but maybe it doesn't make sense.
Thanks for taking time anyway. Feel free to close :)

**Comment by rpominov** [comment]
Thank you for the real example. I've probably misunderstood how `Promise.filter()` works at first. If I got it right this time, you can do something like this:

```js
// using Task

function resolveQuestion(question) {
  return hasQuestionBeenAnswered(question).map(hasAnswer => ({hasAnswer, question}))
}

Task.paralell(questions.map(resolveQuestion)).run(questions2 => {
  const answered = questions2.filter(a => a.hasAnswer).map(a => a.question)
  console.log(answered)
})


// same using Promises (for a better understanding)

function resolveQuestion(question) {
  return hasQuestionBeenAnswered(question).then(hasAnswer => ({hasAnswer, question}))
}

Promise.all(questions.map(resolveQuestion)).then(questions2 => {
  const answered = questions2.filter(a => a.hasAnswer).map(a => a.question)
  console.log(answered)
})
```

**Comment by bachstatter** [comment]
That looks good! Thanks :)
