### ISSUE TITLE
Explanation of exceptions has incorrect image

### ISSUE THREAD

**Issue by SgtPooki** [rpominov/fun-task#37]
![image](https://user-images.githubusercontent.com/1173416/66022257-30701f00-e4a2-11e9-8f09-c344e0135d52.png) 
at https://github.com/rpominov/fun-task/blame/master/docs/exceptions.md#L32-L34

In the first section of the image the `x <= 0` true case in the code shows that you `alert(z + 5)`, but the image shows that you `alert(y + 5)`

In the second section of the image, the `x > 0` should still lead to `y = 10`, or the color should be red to indicate the failure case of the first conditional branch. And then the green path for truth should lead to the `alert(y + 5)` path.

Also, you state that there are two expected results of the program, but your initial if condition doesn't set z or y when x = 0, which is "technically" possible via the Math.random() spec...

**Comment by rpominov** [comment]
I might be missing something, but I think it's all correct.

For the fist image imagine `x` being `0.2`. For the second imagine it being `-0.2`.

> Also, you state that there are two expected results of the program, but your initial if condition doesn't set z or y when x = 0, which is "technically" possible via the Math.random() spec...

If `x` is `0` the `z = 10` branch is ran.
